version: "3"

services:
  apartments:
    build: .
    command:
      sh -c "
      cd src &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py cities_light &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/apartments/
    ports:
      - "8000:8000"

networks:
  default:
    external: true
    name: psql_network
