# Generated by Django 3.2.2 on 2021-05-31 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmessage',
            name='is_seen',
        ),
        migrations.AlterField(
            model_name='bookingmessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_receivers4', to=settings.AUTH_USER_MODEL),
        ),
    ]
