# Generated by Django 3.2.2 on 2021-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210531_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmessage',
            name='is_seen_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingmessage',
            name='is_seen_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
