# Generated by Django 3.2.2 on 2021-06-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210531_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmessage',
            old_name='is_seen_by_client',
            new_name='read',
        ),
        migrations.RemoveField(
            model_name='bookingmessage',
            name='is_seen_by_owner',
        ),
    ]
