# Generated by Django 3.2.2 on 2021-05-17 17:18

import apartments.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('room_amount', models.CharField(choices=[(1, 'одна'), (2, 'две'), (3, 'три'), (4, 'четыре'), (5, 'больше, чем четыре')], max_length=20)),
                ('bedroom_amount', models.CharField(choices=[(1, 'одна'), (2, 'две'), (3, 'три'), (4, 'четыре'), (5, 'больше, чем четыре')], max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('registry_ordering', models.FileField(upload_to='apartments/registry_scans/')),
                ('convenience_items', apartments.fields.ChoiceArrayField(base_field=models.CharField(choices=[('WIFI', 'WiFi'), ('COND', 'Кондиционер'), ('WSHM', 'Стиральная машина'), ('DSHW', 'Посудомоечная машина'), ('HRDR', 'Сушилка для волос'), ('MNBR', 'Минибар'), ('LLPH', 'Стационарный телефон'), ('CLLN', 'Чистое белье')], max_length=50), size=None)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='apartments/images/')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apartments.apartment')),
            ],
        ),
    ]
