# Generated by Django 3.2.2 on 2021-06-03 10:23

import apartments.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('square_area', models.PositiveSmallIntegerField()),
                ('room_amount', models.IntegerField(choices=[(0, 'not specified'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'more')])),
                ('bedroom_amount', models.IntegerField(choices=[(0, 'not specified'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'more')])),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('registry_ordering', models.FileField(upload_to='apartments/registry_scans/')),
                ('convenience_items', apartments.fields.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('WIFI', 'Wi-Fi'), ('COND', 'Conditioner'), ('WSHM', 'Washing machine'), ('DSHW', 'Dishwasher'), ('HRDR', 'Hairdryer'), ('MNBR', 'Minibar'), ('LLPH', 'Landline phone'), ('CLLN', 'Clean linen')], default=None, max_length=50, null=True), size=None)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('opens_at', models.DateField(blank=True, null=True)),
                ('closes_at', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='apartments/images/')),
                ('position', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apartments.apartment')),
            ],
        ),
    ]
