# Generated by Django 3.2.2 on 2021-05-24 14:21

import apartments.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='convenience_items',
            field=apartments.fields.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('WIFI', 'Wi-Fi'), ('COND', 'Conditioner'), ('WSHM', 'Washing machine'), ('DSHW', 'Dishwasher'), ('HRDR', 'Hairdryer'), ('MNBR', 'Minibar'), ('LLPH', 'Landline phone'), ('CLLN', 'Clean linen')], max_length=50, null=True), size=None),
        ),
    ]
