# Generated by Django 3.2.2 on 2021-05-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentphoto',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
