# Generated by Django 3.2.2 on 2021-05-17 18:49

import apartments.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartmentphoto_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='convenience_items',
            field=apartments.fields.ChoiceArrayField(base_field=models.CharField(choices=[('WIFI', 'Wi-Fi'), ('COND', 'Кондиционер'), ('WSHM', 'Стиральная машина'), ('DSHW', 'Посудомоечная машина'), ('HRDR', 'Сушилка для волос'), ('MNBR', 'Минибар'), ('LLPH', 'Стационарный телефон'), ('CLLN', 'Чистое белье')], max_length=50), size=None),
        ),
    ]
