# Generated by Django 3.2.2 on 2021-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_alter_apartment_convenience_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bedroom_amount',
            field=models.IntegerField(choices=[(0, 'not specified'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'more')]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_amount',
            field=models.IntegerField(choices=[(0, 'not specified'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'more')]),
        ),
    ]
