# Generated by Django 3.2.2 on 2021-05-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_apartment_convenience_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bedroom_amount',
            field=models.IntegerField(choices=[(1, 'одна'), (2, 'две'), (3, 'три'), (4, 'четыре'), (5, 'больше, чем четыре')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_amount',
            field=models.IntegerField(choices=[(1, 'одна'), (2, 'две'), (3, 'три'), (4, 'четыре'), (5, 'больше, чем четыре')], max_length=20),
        ),
    ]
