# Generated by Django 3.2.2 on 2021-05-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_auto_20210517_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='datetime_end',
            new_name='ends_at',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='datetime_start',
            new_name='starts_at',
        ),
    ]
